baseURL = 'https://celebrated-tulumba-c25adc.netlify.app/'
languageCode = 'en-us'
title = 'Your Name'
theme = 'PaperMod'

[params]
  homeInfoParams = { Title = "Hi 👋", Content = "I'm a Senior Software Engineer..." }
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
