baseURL = 'https://craig-houston.blog/'
languageCode = 'en-us'
title = 'Craig Houston'
theme = 'PaperMod'

[params]
  homeInfoParams = false
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true